<?php

use App\Services\CommonService as Common;
$QuerryData = Common::getSignatureSettings();

?>
<br><br><br><br>
<!-- <div class="" style="display: flex!important; justify-content: space-around!important;"> -->
<div class="d-flex justify-content-end justify-content-around">
    @if(count($QuerryData) > 0)
    <div class="p-2">
        <div class="card">
            <div class="card-body">
                <p class="card-text">_______________</p>
                <h5 class="card-title">Generated By</h5>
                <p class="card-text">{{Auth::user()->full_name}}</p>
                <p class="card-text">
                  <small class="text-muted">
                    {{Common::getSignatureEmployee(null,null,Auth::id())}}
                  </small>
                </p>
            </div>
        </div>
    </div>
    @endif
    @foreach ($QuerryData as $item)
    <div class="p-2">
        <div class="card">
            <div class="card-body">
                <p class="card-text">_______________</p>
                <h5 class="card-title">{{$item->title}}</h5>
                <p class="card-text">
                    {{(isset($item->signatorEmployeeId)? $item->employee->emp_name : Common::getSignatureEmployee(null,$item->signatorDesignationId))}}
                </p>
                <p class="card-text"><small class="text-muted">{{$item->designation->name}}</small></p>
            </div>
        </div>
    </div>
    @endforeach
</div>
